#!/usr/bin/env php
<?php

namespace Max;

require './vendor/autoload.php';

(new App())->setRootPath('./')->start(function (App $app) {

    $console = $app->console;

    $console->register('./routes/console.php')->run();
});


